# Generated by Django 5.0 on 2023-12-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ui", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                default="tempUser", max_length=150, unique=True, verbose_name="username"
            ),
            preserve_default=False,
        ),
    ]
