# Generated by Django 5.0 on 2023-12-08 23:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ui", "0002_customuser_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="VotingOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vote_id", models.IntegerField(null=True)),
                ("option_number", models.IntegerField()),
                ("option_name", models.CharField(max_length=200)),
            ],
        ),
    ]
