# Generated by Django 5.0 on 2023-12-08 23:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ui", "0003_votingoption"),
    ]

    operations = [
        migrations.AlterField(
            model_name="votingoption",
            name="vote_id",
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
